baseURL = "https://annbelievable.github.io/bubbletea"
languageCode = "en-us"
title = "Hicaa"
theme = "ananke"

[languages]
  [languages.en]
    title = "Hicaa"
    weight = 1
    contentDir = "content/en"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "匠心制茶 不将就"
  background_color_class = "bg-orange"

custom_css = ["css/bubbletea.css"]